<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Warga;
use App\Models\User;

class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first();
        $adminId = $admin ? $admin->id : null;

        $wargas = [
            [
                'nik' => '3201021203750001',
                'nama_lengkap' => 'Ahmad Subagja',
                'alamat' => 'Jl. Mawar No. 12',
                'rt' => '003',
                'rw' => '004',
                'desa' => 'Mekarsari',
                'no_hp' => '085612345678',
                'pekerjaan' => 'Buruh Harian Lepas',
                'penghasilan' => 950000,
                'jumlah_tanggungan' => 4,
                'kondisi_rumah' => 'Buruk (Dinding kayu/bata tanpa plester, atap bocor)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Aset Kecil (Elektronik murah, sepeda)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201021508820002',
                'nama_lengkap' => 'Siti Aminah',
                'alamat' => 'Kampung Babakan RT 01',
                'rt' => '001',
                'rw' => '002',
                'desa' => 'Mekarsari',
                'no_hp' => '087823456789',
                'pekerjaan' => 'Tidak Bekerja / Pengangguran',
                'penghasilan' => 450000,
                'jumlah_tanggungan' => 5,
                'kondisi_rumah' => 'Sangat Buruk (Lantai tanah, dinding bambu, reyot)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Tidak Memiliki Aset Apapun',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201021911790003',
                'nama_lengkap' => 'Budi Santoso',
                'alamat' => 'Dusun Sukamaju',
                'rt' => '002',
                'rw' => '001',
                'desa' => 'Mekarsari',
                'no_hp' => '081334567890',
                'pekerjaan' => 'Karyawan Swasta Tidak Tetap / Wiraswasta Mikro',
                'penghasilan' => 2200000,
                'jumlah_tanggungan' => 3,
                'kondisi_rumah' => 'Cukup (Dinding bata permanen sederhana, semi permanen)',
                'status_bantuan_sebelumnya' => 'Pernah (Selesai)',
                'kepemilikan_aset' => 'Memiliki Motor (1 unit kendaraan roda dua)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201022204850004',
                'nama_lengkap' => 'Supriyono',
                'alamat' => 'Kampung Bojong',
                'rt' => '005',
                'rw' => '003',
                'desa' => 'Sukahening',
                'no_hp' => '082145678901',
                'pekerjaan' => 'Petani Kecil / Nelayan Kecil',
                'penghasilan' => 1200000,
                'jumlah_tanggungan' => 3,
                'kondisi_rumah' => 'Buruk (Dinding kayu/bata tanpa plester, atap bocor)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Aset Kecil (Elektronik murah, sepeda)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201026507900005',
                'nama_lengkap' => 'Dewi Lestari',
                'alamat' => 'Perum Indah Lestari Blok B1',
                'rt' => '002',
                'rw' => '005',
                'desa' => 'Sukahening',
                'no_hp' => '081256789012',
                'pekerjaan' => 'PNS / Karyawan BUMN / Karyawan Tetap Swasta',
                'penghasilan' => 5500000,
                'jumlah_tanggungan' => 2,
                'kondisi_rumah' => 'Sangat Baik (Rumah mewah/besar, bertingkat)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Mobil / Tanah (Aset produktif/bernilai tinggi)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201021402800006',
                'nama_lengkap' => 'Joko Widodo (Warga Mekarsari)',
                'alamat' => 'RT 04 RW 02 Mekarsari',
                'rt' => '004',
                'rw' => '002',
                'desa' => 'Mekarsari',
                'no_hp' => '089967890123',
                'pekerjaan' => 'Buruh Harian Lepas',
                'penghasilan' => 800000,
                'jumlah_tanggungan' => 5,
                'kondisi_rumah' => 'Buruk (Dinding kayu/bata tanpa plester, atap bocor)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Tidak Memiliki Aset Apapun',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201024505880007',
                'nama_lengkap' => 'Rina Kartika',
                'alamat' => 'Kampung Baru RT 01',
                'rt' => '001',
                'rw' => '003',
                'desa' => 'Mekarsari',
                'no_hp' => '085778901234',
                'pekerjaan' => 'Karyawan Swasta Tidak Tetap / Wiraswasta Mikro',
                'penghasilan' => 1500000,
                'jumlah_tanggungan' => 2,
                'kondisi_rumah' => 'Cukup (Dinding bata permanen sederhana, semi permanen)',
                'status_bantuan_sebelumnya' => 'Pernah (Aktif)',
                'kepemilikan_aset' => 'Memiliki Motor (1 unit kendaraan roda dua)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201021111720008',
                'nama_lengkap' => 'Hasan Basri',
                'alamat' => 'Dusun Kidul RT 02',
                'rt' => '002',
                'rw' => '004',
                'desa' => 'Sukahening',
                'no_hp' => '085289012345',
                'pekerjaan' => 'Tidak Bekerja / Pengangguran',
                'penghasilan' => 300000,
                'jumlah_tanggungan' => 1,
                'kondisi_rumah' => 'Sangat Buruk (Lantai tanah, dinding bambu, reyot)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Tidak Memiliki Aset Apapun',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201022809830009',
                'nama_lengkap' => 'Dadang Suherman',
                'alamat' => 'Kampung Sawah RT 03',
                'rt' => '003',
                'rw' => '002',
                'desa' => 'Sukahening',
                'no_hp' => '087790123456',
                'pekerjaan' => 'Petani Kecil / Nelayan Kecil',
                'penghasilan' => 1100000,
                'jumlah_tanggungan' => 4,
                'kondisi_rumah' => 'Buruk (Dinding kayu/bata tanpa plester, atap bocor)',
                'status_bantuan_sebelumnya' => 'Pernah (Selesai)',
                'kepemilikan_aset' => 'Memiliki Aset Kecil (Elektronik murah, sepeda)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201020412850010',
                'nama_lengkap' => 'Rahmat Hidayat',
                'alamat' => 'Jl. Dahlia Indah No. 45',
                'rt' => '001',
                'rw' => '001',
                'desa' => 'Mekarsari',
                'no_hp' => '081290123457',
                'pekerjaan' => 'PNS / Karyawan BUMN / Karyawan Tetap Swasta',
                'penghasilan' => 4200000,
                'jumlah_tanggungan' => 3,
                'kondisi_rumah' => 'Baik (Rumah permanen, bersih, lantai keramik)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Motor (1 unit kendaraan roda dua)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201026012890011',
                'nama_lengkap' => 'Wati Setiawati',
                'alamat' => 'Kampung Rawagede RT 04',
                'rt' => '004',
                'rw' => '001',
                'desa' => 'Mekarsari',
                'no_hp' => '089801234567',
                'pekerjaan' => 'Karyawan Swasta Tidak Tetap / Wiraswasta Mikro',
                'penghasilan' => 1800000,
                'jumlah_tanggungan' => 4,
                'kondisi_rumah' => 'Cukup (Dinding bata permanen sederhana, semi permanen)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Motor (1 unit kendaraan roda dua)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201020505800012',
                'nama_lengkap' => 'Kusnadi',
                'alamat' => 'Kampung Sindang RT 02 RW 03',
                'rt' => '002',
                'rw' => '003',
                'desa' => 'Sukahening',
                'no_hp' => '083812345678',
                'pekerjaan' => 'Buruh Harian Lepas',
                'penghasilan' => 850000,
                'jumlah_tanggungan' => 3,
                'kondisi_rumah' => 'Sangat Buruk (Lantai tanah, dinding bambu, reyot)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Tidak Memiliki Aset Apapun',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201022107750013',
                'nama_lengkap' => 'Mulyono',
                'alamat' => 'Kampung Bojong Lor',
                'rt' => '003',
                'rw' => '004',
                'desa' => 'Mekarsari',
                'no_hp' => '082223456789',
                'pekerjaan' => 'Petani Kecil / Nelayan Kecil',
                'penghasilan' => 1250000,
                'jumlah_tanggungan' => 2,
                'kondisi_rumah' => 'Buruk (Dinding kayu/bata tanpa plester, atap bocor)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Aset Kecil (Elektronik murah, sepeda)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201025510910014',
                'nama_lengkap' => 'Sri Wahyuni',
                'alamat' => 'Perum Mekarsari Elok C4',
                'rt' => '006',
                'rw' => '004',
                'desa' => 'Mekarsari',
                'no_hp' => '085734567890',
                'pekerjaan' => 'PNS / Karyawan BUMN / Karyawan Tetap Swasta',
                'penghasilan' => 6200000,
                'jumlah_tanggungan' => 1,
                'kondisi_rumah' => 'Sangat Baik (Rumah mewah/besar, bertingkat)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Mobil / Tanah (Aset produktif/bernilai tinggi)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201020202720015',
                'nama_lengkap' => 'Cecep Supriadi',
                'alamat' => 'Kampung Caringin RT 02',
                'rt' => '002',
                'rw' => '002',
                'desa' => 'Sukahening',
                'no_hp' => '087845678901',
                'pekerjaan' => 'Buruh Harian Lepas',
                'penghasilan' => 700000,
                'jumlah_tanggungan' => 6,
                'kondisi_rumah' => 'Sangat Buruk (Lantai tanah, dinding bambu, reyot)',
                'status_bantuan_sebelumnya' => 'Pernah (Aktif)',
                'kepemilikan_aset' => 'Tidak Memiliki Aset Apapun',
                'created_by' => $adminId,
            ],
            // Expanded warga for a total of 25 demo citizens
            [
                'nik' => '3201021406830016',
                'nama_lengkap' => 'Suherman Wijaya',
                'alamat' => 'Dusun Karangtengah',
                'rt' => '001',
                'rw' => '003',
                'desa' => 'Ringinarum',
                'no_hp' => '081223344556',
                'pekerjaan' => 'Buruh Harian Lepas',
                'penghasilan' => 750000,
                'jumlah_tanggungan' => 5,
                'kondisi_rumah' => 'Sangat Buruk (Lantai tanah, dinding bambu, reyot)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Tidak Memiliki Aset Apapun',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201025205840017',
                'nama_lengkap' => 'Kartini Saputri',
                'alamat' => 'Jl. Pemuda No. 8',
                'rt' => '002',
                'rw' => '001',
                'desa' => 'Ringinarum',
                'no_hp' => '085334455667',
                'pekerjaan' => 'Tidak Bekerja / Pengangguran',
                'penghasilan' => 500000,
                'jumlah_tanggungan' => 4,
                'kondisi_rumah' => 'Buruk (Dinding kayu/bata tanpa plester, atap bocor)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Aset Kecil (Elektronik murah, sepeda)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201021102710018',
                'nama_lengkap' => 'Slamet Riyadi',
                'alamat' => 'Kampung Sawah Lor',
                'rt' => '005',
                'rw' => '002',
                'desa' => 'Ringinarum',
                'no_hp' => '089887766554',
                'pekerjaan' => 'Petani Kecil / Nelayan Kecil',
                'penghasilan' => 1050000,
                'jumlah_tanggungan' => 3,
                'kondisi_rumah' => 'Buruk (Dinding kayu/bata tanpa plester, atap bocor)',
                'status_bantuan_sebelumnya' => 'Pernah (Selesai)',
                'kepemilikan_aset' => 'Tidak Memiliki Aset Apapun',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201026608920019',
                'nama_lengkap' => 'Hartati Ningsih',
                'alamat' => 'Perum Ringin Asri C-12',
                'rt' => '003',
                'rw' => '005',
                'desa' => 'Ringinarum',
                'no_hp' => '081335577991',
                'pekerjaan' => 'PNS / Karyawan BUMN / Karyawan Tetap Swasta',
                'penghasilan' => 4800000,
                'jumlah_tanggungan' => 2,
                'kondisi_rumah' => 'Baik (Rumah permanen, bersih, lantai keramik)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Motor (1 unit kendaraan roda dua)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201020709770020',
                'nama_lengkap' => 'Agus Priyono',
                'alamat' => 'Jl. Pahlawan Gg. 3',
                'rt' => '004',
                'rw' => '004',
                'desa' => 'Ringinarum',
                'no_hp' => '087711223344',
                'pekerjaan' => 'Karyawan Swasta Tidak Tetap / Wiraswasta Mikro',
                'penghasilan' => 1950000,
                'jumlah_tanggungan' => 3,
                'kondisi_rumah' => 'Cukup (Dinding bata permanen sederhana, semi permanen)',
                'status_bantuan_sebelumnya' => 'Pernah (Aktif)',
                'kepemilikan_aset' => 'Memiliki Motor (1 unit kendaraan roda dua)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201020104860021',
                'nama_lengkap' => 'Bambang Hermawan',
                'alamat' => 'Kampung Bojong RT 03',
                'rt' => '003',
                'rw' => '003',
                'desa' => 'Ringinarum',
                'no_hp' => '082188990011',
                'pekerjaan' => 'Buruh Harian Lepas',
                'penghasilan' => 900000,
                'jumlah_tanggungan' => 4,
                'kondisi_rumah' => 'Sangat Buruk (Lantai tanah, dinding bambu, reyot)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Tidak Memiliki Aset Apapun',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201024310880022',
                'nama_lengkap' => 'Tri Astuti',
                'alamat' => 'Kampung Baru Barat',
                'rt' => '001',
                'rw' => '004',
                'desa' => 'Ringinarum',
                'no_hp' => '085699008877',
                'pekerjaan' => 'Tidak Bekerja / Pengangguran',
                'penghasilan' => 400000,
                'jumlah_tanggungan' => 5,
                'kondisi_rumah' => 'Sangat Buruk (Lantai tanah, dinding bambu, reyot)',
                'status_bantuan_sebelumnya' => 'Pernah (Selesai)',
                'kepemilikan_aset' => 'Tidak Memiliki Aset Apapun',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201022912800023',
                'nama_lengkap' => 'Jafar Shodiq',
                'alamat' => 'Dusun Krajan RT 02',
                'rt' => '002',
                'rw' => '002',
                'desa' => 'Ringinarum',
                'no_hp' => '087855663322',
                'pekerjaan' => 'Petani Kecil / Nelayan Kecil',
                'penghasilan' => 1150000,
                'jumlah_tanggungan' => 2,
                'kondisi_rumah' => 'Buruk (Dinding kayu/bata tanpa plester, atap bocor)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Aset Kecil (Elektronik murah, sepeda)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201020211750024',
                'nama_lengkap' => 'Sudarno',
                'alamat' => 'Kampung Karangasri',
                'rt' => '006',
                'rw' => '001',
                'desa' => 'Ringinarum',
                'no_hp' => '089677889900',
                'pekerjaan' => 'Karyawan Swasta Tidak Tetap / Wiraswasta Mikro',
                'penghasilan' => 2100000,
                'jumlah_tanggungan' => 3,
                'kondisi_rumah' => 'Cukup (Dinding bata permanen sederhana, semi permanen)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Motor (1 unit kendaraan roda dua)',
                'created_by' => $adminId,
            ],
            [
                'nik' => '3201025501900025',
                'nama_lengkap' => 'Indah Permatasari',
                'alamat' => 'Jl. Sudirman No. 56',
                'rt' => '001',
                'rw' => '001',
                'desa' => 'Ringinarum',
                'no_hp' => '081299001122',
                'pekerjaan' => 'PNS / Karyawan BUMN / Karyawan Tetap Swasta',
                'penghasilan' => 6000000,
                'jumlah_tanggungan' => 1,
                'kondisi_rumah' => 'Sangat Baik (Rumah mewah/besar, bertingkat)',
                'status_bantuan_sebelumnya' => 'Belum Pernah',
                'kepemilikan_aset' => 'Memiliki Mobil / Tanah (Aset produktif/bernilai tinggi)',
                'created_by' => $adminId,
            ],
        ];

        foreach ($wargas as $warga) {
            Warga::create($warga);
        }
    }
}
